name: expyr_assignment_1
description: Assignment 1 for Expyr app - Consumed Goods Tracking
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
          style: normal

  # Don't forget to keep your existing assets
  assets:
    - assets/fonts/
